// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TYPE_BUGAT_PACKET_GAME_H_
#define FLATBUFFERS_GENERATED_TYPE_BUGAT_PACKET_GAME_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace bugat {
namespace packet {
namespace game {

enum class Type : int16_t {
  Weapon = 1,
  Monster = 2,
  MIN = Weapon,
  MAX = Monster
};

inline const Type (&EnumValuesType())[2] {
  static const Type values[] = {
    Type::Weapon,
    Type::Monster
  };
  return values;
}

inline const char * const *EnumNamesType() {
  static const char * const names[3] = {
    "Weapon",
    "Monster",
    nullptr
  };
  return names;
}

inline const char *EnumNameType(Type e) {
  if (::flatbuffers::IsOutRange(e, Type::Weapon, Type::Monster)) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(Type::Weapon);
  return EnumNamesType()[index];
}

}  // namespace game
}  // namespace packet
}  // namespace bugat

#endif  // FLATBUFFERS_GENERATED_TYPE_BUGAT_PACKET_GAME_H_
