// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_USER_BUGAT_PACKET_GAME_H_
#define FLATBUFFERS_GENERATED_USER_BUGAT_PACKET_GAME_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace bugat {
namespace packet {
namespace game {

struct ReqCS_Login;
struct ReqCS_LoginBuilder;

struct ResSC_Login;
struct ResSC_LoginBuilder;

struct ReqCS_Login FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ReqCS_LoginBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_PW = 6
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *pw() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PW);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_PW) &&
           verifier.VerifyString(pw()) &&
           verifier.EndTable();
  }
};

struct ReqCS_LoginBuilder {
  typedef ReqCS_Login Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(ReqCS_Login::VT_ID, id);
  }
  void add_pw(::flatbuffers::Offset<::flatbuffers::String> pw) {
    fbb_.AddOffset(ReqCS_Login::VT_PW, pw);
  }
  explicit ReqCS_LoginBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ReqCS_Login> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ReqCS_Login>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ReqCS_Login> CreateReqCS_Login(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> pw = 0) {
  ReqCS_LoginBuilder builder_(_fbb);
  builder_.add_pw(pw);
  builder_.add_id(id);
  return builder_.Finish();
}

struct ReqCS_Login::Traits {
  using type = ReqCS_Login;
  static auto constexpr Create = CreateReqCS_Login;
};

inline ::flatbuffers::Offset<ReqCS_Login> CreateReqCS_LoginDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *pw = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto pw__ = pw ? _fbb.CreateString(pw) : 0;
  return bugat::packet::game::CreateReqCS_Login(
      _fbb,
      id__,
      pw__);
}

struct ResSC_Login FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ResSC_LoginBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PID = 4
  };
  uint64_t pid() const {
    return GetField<uint64_t>(VT_PID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_PID, 8) &&
           verifier.EndTable();
  }
};

struct ResSC_LoginBuilder {
  typedef ResSC_Login Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pid(uint64_t pid) {
    fbb_.AddElement<uint64_t>(ResSC_Login::VT_PID, pid, 0);
  }
  explicit ResSC_LoginBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ResSC_Login> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ResSC_Login>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ResSC_Login> CreateResSC_Login(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t pid = 0) {
  ResSC_LoginBuilder builder_(_fbb);
  builder_.add_pid(pid);
  return builder_.Finish();
}

struct ResSC_Login::Traits {
  using type = ResSC_Login;
  static auto constexpr Create = CreateResSC_Login;
};

inline const bugat::packet::game::ResSC_Login *GetResSC_Login(const void *buf) {
  return ::flatbuffers::GetRoot<bugat::packet::game::ResSC_Login>(buf);
}

inline const bugat::packet::game::ResSC_Login *GetSizePrefixedResSC_Login(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<bugat::packet::game::ResSC_Login>(buf);
}

inline bool VerifyResSC_LoginBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<bugat::packet::game::ResSC_Login>(nullptr);
}

inline bool VerifySizePrefixedResSC_LoginBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<bugat::packet::game::ResSC_Login>(nullptr);
}

inline void FinishResSC_LoginBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<bugat::packet::game::ResSC_Login> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedResSC_LoginBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<bugat::packet::game::ResSC_Login> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace game
}  // namespace packet
}  // namespace bugat

#endif  // FLATBUFFERS_GENERATED_USER_BUGAT_PACKET_GAME_H_
