// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PLAYER_BUGAT_PROTOCOL_GAME_H_
#define FLATBUFFERS_GENERATED_PLAYER_BUGAT_PROTOCOL_GAME_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace bugat {
namespace protocol {
namespace game {

struct FVec3;

struct Req_CS_Move;
struct Req_CS_MoveBuilder;

struct Res_SC_Move;
struct Res_SC_MoveBuilder;

struct Bcast_SC_Move;
struct Bcast_SC_MoveBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) FVec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  struct Traits;
  FVec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  FVec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(FVec3, 12);

struct FVec3::Traits {
  using type = FVec3;
};

struct Req_CS_Move FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Req_CS_MoveBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POS = 4
  };
  const bugat::protocol::game::FVec3 *pos() const {
    return GetStruct<const bugat::protocol::game::FVec3 *>(VT_POS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<bugat::protocol::game::FVec3>(verifier, VT_POS, 4) &&
           verifier.EndTable();
  }
};

struct Req_CS_MoveBuilder {
  typedef Req_CS_Move Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pos(const bugat::protocol::game::FVec3 *pos) {
    fbb_.AddStruct(Req_CS_Move::VT_POS, pos);
  }
  explicit Req_CS_MoveBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Req_CS_Move> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Req_CS_Move>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Req_CS_Move> CreateReq_CS_Move(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const bugat::protocol::game::FVec3 *pos = nullptr) {
  Req_CS_MoveBuilder builder_(_fbb);
  builder_.add_pos(pos);
  return builder_.Finish();
}

struct Req_CS_Move::Traits {
  using type = Req_CS_Move;
  static auto constexpr Create = CreateReq_CS_Move;
};

struct Res_SC_Move FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Res_SC_MoveBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POS = 4
  };
  const bugat::protocol::game::FVec3 *pos() const {
    return GetStruct<const bugat::protocol::game::FVec3 *>(VT_POS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<bugat::protocol::game::FVec3>(verifier, VT_POS, 4) &&
           verifier.EndTable();
  }
};

struct Res_SC_MoveBuilder {
  typedef Res_SC_Move Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pos(const bugat::protocol::game::FVec3 *pos) {
    fbb_.AddStruct(Res_SC_Move::VT_POS, pos);
  }
  explicit Res_SC_MoveBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Res_SC_Move> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Res_SC_Move>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Res_SC_Move> CreateRes_SC_Move(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const bugat::protocol::game::FVec3 *pos = nullptr) {
  Res_SC_MoveBuilder builder_(_fbb);
  builder_.add_pos(pos);
  return builder_.Finish();
}

struct Res_SC_Move::Traits {
  using type = Res_SC_Move;
  static auto constexpr Create = CreateRes_SC_Move;
};

struct Bcast_SC_Move FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Bcast_SC_MoveBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_POS = 6
  };
  int64_t id() const {
    return GetField<int64_t>(VT_ID, 0);
  }
  const bugat::protocol::game::FVec3 *pos() const {
    return GetStruct<const bugat::protocol::game::FVec3 *>(VT_POS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_ID, 8) &&
           VerifyField<bugat::protocol::game::FVec3>(verifier, VT_POS, 4) &&
           verifier.EndTable();
  }
};

struct Bcast_SC_MoveBuilder {
  typedef Bcast_SC_Move Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int64_t id) {
    fbb_.AddElement<int64_t>(Bcast_SC_Move::VT_ID, id, 0);
  }
  void add_pos(const bugat::protocol::game::FVec3 *pos) {
    fbb_.AddStruct(Bcast_SC_Move::VT_POS, pos);
  }
  explicit Bcast_SC_MoveBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Bcast_SC_Move> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Bcast_SC_Move>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Bcast_SC_Move> CreateBcast_SC_Move(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t id = 0,
    const bugat::protocol::game::FVec3 *pos = nullptr) {
  Bcast_SC_MoveBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_pos(pos);
  return builder_.Finish();
}

struct Bcast_SC_Move::Traits {
  using type = Bcast_SC_Move;
  static auto constexpr Create = CreateBcast_SC_Move;
};

}  // namespace game
}  // namespace protocol
}  // namespace bugat

#endif  // FLATBUFFERS_GENERATED_PLAYER_BUGAT_PROTOCOL_GAME_H_
