// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TYPE_BUGAT_PROTOCOL_GAME_H_
#define FLATBUFFERS_GENERATED_TYPE_BUGAT_PROTOCOL_GAME_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace bugat {
namespace protocol {
namespace game {

enum class Type : int16_t {
  REQ_CS_LOGIN = 1,
  RES_SC_LOGIN = 2,
  REQ_CS_MOVE = 3,
  RES_SC_MOVE = 4,
  REQ_CS_EQUIP = 5,
  RES_SC_EQUIP = 6,
  Bcast_SC_Move = 600,
  MIN = REQ_CS_LOGIN,
  MAX = Bcast_SC_Move
};

inline const Type (&EnumValuesType())[7] {
  static const Type values[] = {
    Type::REQ_CS_LOGIN,
    Type::RES_SC_LOGIN,
    Type::REQ_CS_MOVE,
    Type::RES_SC_MOVE,
    Type::REQ_CS_EQUIP,
    Type::RES_SC_EQUIP,
    Type::Bcast_SC_Move
  };
  return values;
}

inline const char *EnumNameType(Type e) {
  switch (e) {
    case Type::REQ_CS_LOGIN: return "REQ_CS_LOGIN";
    case Type::RES_SC_LOGIN: return "RES_SC_LOGIN";
    case Type::REQ_CS_MOVE: return "REQ_CS_MOVE";
    case Type::RES_SC_MOVE: return "RES_SC_MOVE";
    case Type::REQ_CS_EQUIP: return "REQ_CS_EQUIP";
    case Type::RES_SC_EQUIP: return "RES_SC_EQUIP";
    case Type::Bcast_SC_Move: return "Bcast_SC_Move";
    default: return "";
  }
}

}  // namespace game
}  // namespace protocol
}  // namespace bugat

#endif  // FLATBUFFERS_GENERATED_TYPE_BUGAT_PROTOCOL_GAME_H_
