// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_USER_BUGAT_PROTOCOL_GAME_H_
#define FLATBUFFERS_GENERATED_USER_BUGAT_PROTOCOL_GAME_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace bugat {
namespace protocol {
namespace game {

struct Req_CS_Login;
struct Req_CS_LoginBuilder;

struct Res_SC_Login;
struct Res_SC_LoginBuilder;

struct Req_CS_Login FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Req_CS_LoginBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_PW = 6
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *pw() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PW);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_PW) &&
           verifier.VerifyString(pw()) &&
           verifier.EndTable();
  }
};

struct Req_CS_LoginBuilder {
  typedef Req_CS_Login Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(Req_CS_Login::VT_ID, id);
  }
  void add_pw(::flatbuffers::Offset<::flatbuffers::String> pw) {
    fbb_.AddOffset(Req_CS_Login::VT_PW, pw);
  }
  explicit Req_CS_LoginBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Req_CS_Login> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Req_CS_Login>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Req_CS_Login> CreateReq_CS_Login(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> pw = 0) {
  Req_CS_LoginBuilder builder_(_fbb);
  builder_.add_pw(pw);
  builder_.add_id(id);
  return builder_.Finish();
}

struct Req_CS_Login::Traits {
  using type = Req_CS_Login;
  static auto constexpr Create = CreateReq_CS_Login;
};

inline ::flatbuffers::Offset<Req_CS_Login> CreateReq_CS_LoginDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *pw = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto pw__ = pw ? _fbb.CreateString(pw) : 0;
  return bugat::protocol::game::CreateReq_CS_Login(
      _fbb,
      id__,
      pw__);
}

struct Res_SC_Login FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Res_SC_LoginBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PID = 4
  };
  uint64_t pid() const {
    return GetField<uint64_t>(VT_PID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_PID, 8) &&
           verifier.EndTable();
  }
};

struct Res_SC_LoginBuilder {
  typedef Res_SC_Login Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pid(uint64_t pid) {
    fbb_.AddElement<uint64_t>(Res_SC_Login::VT_PID, pid, 0);
  }
  explicit Res_SC_LoginBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Res_SC_Login> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Res_SC_Login>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Res_SC_Login> CreateRes_SC_Login(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t pid = 0) {
  Res_SC_LoginBuilder builder_(_fbb);
  builder_.add_pid(pid);
  return builder_.Finish();
}

struct Res_SC_Login::Traits {
  using type = Res_SC_Login;
  static auto constexpr Create = CreateRes_SC_Login;
};

}  // namespace game
}  // namespace protocol
}  // namespace bugat

#endif  // FLATBUFFERS_GENERATED_USER_BUGAT_PROTOCOL_GAME_H_
