// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace bugat.protocol.game
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Req_CA_Login : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static Req_CA_Login GetRootAsReq_CA_Login(ByteBuffer _bb) { return GetRootAsReq_CA_Login(_bb, new Req_CA_Login()); }
  public static Req_CA_Login GetRootAsReq_CA_Login(ByteBuffer _bb, Req_CA_Login obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyReq_CA_Login(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, Req_CA_LoginVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Req_CA_Login __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Id { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetIdArray() { return __p.__vector_as_array<byte>(4); }
  public string Pw { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPwBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetPwBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetPwArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<bugat.protocol.game.Req_CA_Login> CreateReq_CA_Login(FlatBufferBuilder builder,
      StringOffset idOffset = default(StringOffset),
      StringOffset pwOffset = default(StringOffset)) {
    builder.StartTable(2);
    Req_CA_Login.AddPw(builder, pwOffset);
    Req_CA_Login.AddId(builder, idOffset);
    return Req_CA_Login.EndReq_CA_Login(builder);
  }

  public static void StartReq_CA_Login(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddId(FlatBufferBuilder builder, StringOffset idOffset) { builder.AddOffset(0, idOffset.Value, 0); }
  public static void AddPw(FlatBufferBuilder builder, StringOffset pwOffset) { builder.AddOffset(1, pwOffset.Value, 0); }
  public static Offset<bugat.protocol.game.Req_CA_Login> EndReq_CA_Login(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<bugat.protocol.game.Req_CA_Login>(o);
  }
  public static void FinishReq_CA_LoginBuffer(FlatBufferBuilder builder, Offset<bugat.protocol.game.Req_CA_Login> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedReq_CA_LoginBuffer(FlatBufferBuilder builder, Offset<bugat.protocol.game.Req_CA_Login> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class Req_CA_LoginVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Id*/, false)
      && verifier.VerifyString(tablePos, 6 /*Pw*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
