// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace bugat.protocol.game
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Res_AC_Login : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static Res_AC_Login GetRootAsRes_AC_Login(ByteBuffer _bb) { return GetRootAsRes_AC_Login(_bb, new Res_AC_Login()); }
  public static Res_AC_Login GetRootAsRes_AC_Login(ByteBuffer _bb, Res_AC_Login obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Res_AC_Login __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Pid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<bugat.protocol.game.Res_AC_Login> CreateRes_AC_Login(FlatBufferBuilder builder,
      ulong pid = 0) {
    builder.StartTable(1);
    Res_AC_Login.AddPid(builder, pid);
    return Res_AC_Login.EndRes_AC_Login(builder);
  }

  public static void StartRes_AC_Login(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPid(FlatBufferBuilder builder, ulong pid) { builder.AddUlong(0, pid, 0); }
  public static Offset<bugat.protocol.game.Res_AC_Login> EndRes_AC_Login(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<bugat.protocol.game.Res_AC_Login>(o);
  }
}


static public class Res_AC_LoginVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Pid*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
