// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace bugat.protocol.game
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Res_SC_Move : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static Res_SC_Move GetRootAsRes_SC_Move(ByteBuffer _bb) { return GetRootAsRes_SC_Move(_bb, new Res_SC_Move()); }
  public static Res_SC_Move GetRootAsRes_SC_Move(ByteBuffer _bb, Res_SC_Move obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Res_SC_Move __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bugat.protocol.game.FVec3? Pos { get { int o = __p.__offset(4); return o != 0 ? (bugat.protocol.game.FVec3?)(new bugat.protocol.game.FVec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartRes_SC_Move(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPos(FlatBufferBuilder builder, Offset<bugat.protocol.game.FVec3> posOffset) { builder.AddStruct(0, posOffset.Value, 0); }
  public static Offset<bugat.protocol.game.Res_SC_Move> EndRes_SC_Move(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<bugat.protocol.game.Res_SC_Move>(o);
  }
}


static public class Res_SC_MoveVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Pos*/, 12 /*bugat.protocol.game.FVec3*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
