// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace bugat.protocol.game
{

public enum Type : short
{
  REQ_CS_LOGIN = 1,
  RES_SC_LOGIN = 2,
  REQ_CS_MOVE = 3,
  RES_SC_MOVE = 4,
  REQ_CS_EQUIP = 5,
  RES_SC_EQUIP = 6,
  Bcast_SC_Move = 600,
};


}
